### PR TITLE
Enable TravisCI for EUPS

### PR DESCRIPTION
**Pull request by mjuric**
I put together a TravisCI config file that tests installing of EUPS and running tests (against Miniconda Python 2.7, for now -- for some reason, it has issues with running in TravisCI's `virtualenv`). I also modified the `README` to add the build pass/fail badge. You can see the result at https://github.com/mjuric/eups

@RobertLuptonTheGood, to enable Travis for this repository, sign in with your GitHub credentials at https://travis-ci.org and enable CI for the EUPS repository. Once that's done, it will rebuild on the next push.

### CODE REVIEW

**Comment by timj** [comment]
Why can't we have a 3.5 one as well?

**Comment by mjuric** [comment]
@timj One step at a time :).
@migueldvb There's a `cd tests` on line 17, so `python testAll.py` should be correct.

**Comment by migueldvb** [comment]
Sorry, I missed the `cd tests` line.

**Comment by mjuric** [comment]
@timj Now with Python 3.5 support.

**Comment by RobertLuptonTheGood** [comment]
Sorry for the delay

**Pull request merged**
