### PR TITLE
Fix75

### LINKED ISSUE #75: Cannot declare packages: eups declare: Can't mix absolute and relative paths
If I install the current master fa02996 using

    ./configure --prefix=/Users/rowen/UW/LSST/lsstsw/eups/master --with-eups=/Users/rowen/UW/LSST/lsstsw/stack --with-python=/usr/bin/python
    make
    make install
    cd /Users/rowen/UW/LSST/lsstsw/eups/
    rm current
    ln -s master current

then setup my stack, I find that I cannot declare packages. For example:

    localhost$ eups declare -r . pipe_base git
    Warning: path /Users/rowen/UW/LSST/lsstsw/build/pipe_base is absolute, not relative to EUPS_PATH
    eups declare: Can't mix absolute and relative paths

This same error is also seen in many of the unit tests, e.g. if after installing eups as above I run "make install" in the original eups repo directory. I'm assuming lsstsw installs eups some other way, perhaps with a relative paty. But I also think eups should be robust enough to handle the above.

Note that the error occurs in the `commonpath` function in `utils.py`. I am very puzzled why that function cannot handle a mix of absolute and relative paths. One possible approach is run os.path.abspath on all inputs, so they are always absolute. That would be robust but it might upset other aspects of eups.

I'm also puzzled why the function `commonpath` exists instead of using `os.path.commonprefix`, and why `commonpath` uses uses card-coded values for path separator and current directory instead of using `os.path.split` and `join`.

### PR DESCRIPTION
**Pull request by r-owen**
Fix #75 Cannot declare packages: eups declare: Can't mix absolute and relative paths as described on that issue.

Note that this makes a number of unit tests pass that failed for me before (though I am not sure they would fail for all users; I think it depends on how one installs eups).

Also fixed two bugs in tests/testDyldLibraryPath.py
- it could only be run from the test directory (which is not where "make tests" ran it)
- the failure message relied on a non-existent variable

### CODE REVIEW

**Comment by timj** [comment]
Looks good to me.

**Comment by migueldvb** [comment]
Apart from changing isSubdir everything looks great

**Comment by mjuric** [comment]
@r-owen Could you rebase this to current master (there are merge conflicts right now), and I'll merge it.

**Comment by r-owen** [comment]
I merged this in 6d1d657

**Pull request closed without merging**
