### PR TITLE
Fix much of issue 72

### PR DESCRIPTION
**Pull request by r-owen**
This pull request goes a long way to fixing issue https://github.com/RobertLuptonTheGood/eups/issues/72. It cleans up the db and distrib sub-packages of eups, including fixing a half dozen or so errors involving undefined variables.

It leaves one important bug unfixed:

server.py has the following incorrect bit of code:

        for versName in (inVersion, "any") or fnmatch.fnmatch(inVersion, versName):
            if versName in self._mapping[flavor][inProduct]:

Without the `or fnmatch...` it makes sense. I have no idea what the bit involving the fnmatch is trying to do, so I don't know how to fix this. I have emailed several people, including Paul Price (who is credited with having been the last to edit the first of these lines).

Note: I suggest doing all of the following before merging this branch:
- Fix issue #66 (e.g. using my branch)
- Test eups distrib and db
- Rebase this branch to master

### CODE REVIEW

**Comment by timj** [comment]
`macrore` was added in commit f8f841bb04ce55e12604b868d8f8765aa202237a and 1ca458988f7f2bd6b0eb581c097d439c39bd3452

**Comment by timj** [comment]
`macrore` was removed in commit 1ca458988f7f2bd6b0eb581c097d439c39bd3452 but that vestigial reference remained.

**Comment by timj** [comment]
For `versName` @PaulPrice twiddled with that code a bit in commit c9520fc95a1ad659bd41bea66e1250ac0d795cd6

@RobertLuptonTheGood first added the `fnmatch` code in 74a6b3e8695f2dd4badbfddf7863a660df0aa5e3

**Comment by r-owen** [comment]
@timj I think macrore was a mistake on my part. Pyflakes complains about it being undefined, but it is defined in my copy -- I just missed the fact. Adding "global macrore" makes pyflakes happy, but I'm not sure it's worth doing.

Thank you for finding the original commit for fnmatch! I've sent email and hope somebody figures it out. I guess there is no rush, as we've been living with it for years, but I hate to leave known bugs lying around.

**Comment by r-owen** [comment]
The or clause was discussed on issue #72. It is a no-op, so I removed it.

**Comment by mjuric** [comment]
I'd propose to also modify the comment at https://github.com/RobertLuptonTheGood/eups/blob/master/python/eups/distrib/server.py#L1837 claiming that you can use a matching glob (e.g., maybe just stick in "THIS IS CURRENTLY BROKEN", with a reference to #72, or something like that).

**Comment by r-owen** [comment]
@mjuric Good idea. I will do that and rebase the last commit.

**Comment by migueldvb** [comment]
Another thing that could be fixed in server.py is replacing the not boolean in
```
if not (k in self.validConfigKeys):
````
by the not in operator that is easier to read.
```
if k not in self.validConfigKeys:
````

**Comment by r-owen** [comment]
OK. I pushed that.

Note that there is a lot of use of open without a context manager, but that would require extensive changes and I think is out of scope.

**Comment by migueldvb** [comment]
There is an if statement in `Repository.py`  simplifiable to a single line that could also be included in this PR. The if statement  test starts in line 104 of @r-owen's fix72 branch:

```
                if "TRUE".startswith(self.options["alwaysQueryServer"]):                 
                    self.options["alwaysQueryServer"] = True                             
                else:                                                                    
                    self.options["alwaysQueryServer"] = False                            
 ```
This can be replaced by
```
self.options["alwaysQueryServer"] = \                                    
                        "TRUE".startswith(self.options["alwaysQueryServer"])
```

**Comment by r-owen** [comment]
I would rather use a different branch for this sort of thing. I feel that the existing branch already has a lot on it.

One cleanup that may be worth doing is to replace:
fd = open(path)
with
with open(path) as fd

in most cases the existing code is probably fine, but messier than it needs to be — especially the old code uses two try blocks because very old python didn’t support try/except/finally as a single block.

If open failures are to be reported more verbosely or otherwise handled specially, then the open file can be used as a context manager (a fact I had not known; I found it on Stack Exchange yesterday):

try:
    fd = open(path)
except Exception as e:
    raise RuntimeError(“Cannot open %s: %s” % (path, e))

with fd:
    ….

— Russell

**Pull request merged**
