### PR TITLE
Prevent DYLD_LIBRARY_PATH from being clobbered on OS X El Capitan

### PR DESCRIPTION
**Pull request by mjuric**
This PR should resolve issue #53.

The patchset has three logical pieces:
* change `eups_setup` (actually, `eups_setup_impl`) to recognize arguments of the form `FOO=bar` and add them to its environment. For example, running `eups_setup FOO=bar blah` will have the same effect as `/usr/bin/env FOO=bar eups_setup blah`.
* rework generated `setups.c?sh` scripts to use EUPS' `eups_setup` mechanism to `setup` the actual `ups/eups.table` table file, instead of repeating that code when generating the `setups.c?sh` scripts. This reduces code duplication (though doesn't eliminate it entirely). Also allows for some hacks in EUPS code to be removed.
* change the definition of `setup` and `unsetup` aliases to always pass `DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH` as an argument to `eups_setup`. This makes it possible for that variable to survive El Capitan's SIP.

I also have two scripts (`test-setups.sh` and `test-setups.sh`) to test this; just run them and inspect the output (these need to be turned into proper unit tests before merging, I know...).

Make sure to run `configure` before testing, i.e., something like `./configure --prefix=$PWD`; otherwise the new `setups` scripts (and the modified EUPS table file) won't be regenerated.

### CODE REVIEW

**Comment by r-owen** [comment]
I am having trouble testing your changes. What I did was:
$ ./configure --with-python=/usr/bin/python --prefix=/Users/rowen/SDSS3/code/zinstalled
$ make
$ make install

which was a mistake because this overwrite my zinstalled directory instead of putting eups in a subdir, as I had expected. Oops. I then restored the "zinstalled" dir from a backup and tried again with:

$ ./configure --with-python=/usr/bin/python --prefix=/Users/rowen/SDSS3/code/zinstalled/eups-test
$ make
$ make install

This time it installed stuff where I expected, but the bin directory was empty. As a result I cannot actually tell if the new eups is behaving. I will attach a terminal log showing the
[Log of my attempts to build eups.txt](https://github.com/RobertLuptonTheGood/eups/files/77535/Log.of.my.attempts.to.build.eups.txt)
 details.

**Comment by mjuric** [comment]
@r-owen Ah, sorry about that. I see the problem, fix is on the way.

**Comment by mjuric** [comment]
@r-owen try now. Fixed two other (unrelated) installation bugs as I was looking into this (we really need to start CI-ing EUPS :( ).

**Comment by r-owen** [comment]
Thank you for the quick fix. That got me a lot further, but sourcing setups.sh fails with an error message:

    Remember to source /Users/rowen/SDSS3/code/zinstalled/eups-test/bin/setups.{c,z,}sh
    localhost$ ls /Users/rowen/SDSS3/code/zinstalled/eups-test/bin
    Makefile        eups_impl.py        eups_setup      eups_setup_impl.pyc mksetup         setups.csh      setups.zsh
    eups            eups_impl.pyc       eups_setup_impl.py  eupspkg         pkgautoversion      setups.sh
    localhost$ source /Users/rowen/SDSS3/code/zinstalled/eups-test/bin/setups.sh
    setup: You chose product DYLD_LIBRARY_PATH=, but I can't find its table file in /Users/rowen/SDSS3/code/zinstalled/eups-master/ups

I did the following to see this:
- Pulled your latest changes
- Recursively deleted `/Users/rowen/SDSS3/code/zinstalled/eups-test/`
- `./configure --with-python=/usr/bin/python --prefix=/Users/rowen/SDSS3/code/zinstalled/eups-test`
- `make`
- `make install`

**Comment by r-owen** [comment]
That error message may have been a one-off (perhaps a side effect of still being logged into the session I used to build eups). I cannot reproduce it with subsequent logins and the new eups appears to be working perfectly.

**Comment by mjuric** [comment]
I think this was left-over state from the previous shell. It's best to open a clean session after updating EUPS.

Unless I hear there are problems, I'll clean up the patch set and merge later today (or tomorrow).

**Pull request merged**
