### PR TITLE
Replace basestring type by str for python 3 compatibility

### PR DESCRIPTION
**Pull request by migueldvb**
This should work in python 2 as well.

### CODE REVIEW

**Comment by migueldvb** [comment]
@PaulPrice  should we use something like?

```
try:
    basestring
except NameError:
    basestring = str
```

**Comment by PaulPrice** [comment]
Is this something you can pull from `__future__`?

**Comment by migueldvb** [comment]
These are the two alternatives I have found using the `future` module:
http://python-future.org/compatible_idioms.html#basestring

**Comment by mjuric** [comment]
Hi @PaulPrice -- does it really need to be a `basestring`? I don't see any piece of code depending on this. I.e., there's nothing that's `unicode` elsewhere in the codebase (in 2.7), so all strings are `str`s. Is there anything in your `startup.py` that's using this?

**Comment by PaulPrice** [comment]
I'm not certain it's completely necessary, but it's the Right Thing To Do, and the tag names are external to the code so maybe they can be unicode?

**Comment by mjuric** [comment]
Thing is, EUPS is not unicode-safe (in 2.7) and I doubt we can ever get it to be (it'd be a *significant* effort). E.g., in this particular example, if a unicode string got passed as a tag, I think you'd get an exception thrown when the code calls `registerTag` because of the [comparison to str here](https://github.com/migueldvb/eups/blob/fix-tests/python/eups/tags.py#L149).

I think it's better to remain consistent -- all other comparisons in the codebase are to `str`. IMHO, this is the right thing to do, even in the absence of Python 3 compatibility problem -- otherwise someone will think there really *is* a practical reason for having `basestring` there, and may spend time pondering what it is (as have I :) ).

**Pull request merged**
