### PR TITLE
Add CXX_CXX14_FLAG

### PR DESCRIPTION
**Pull request by fritzm**

### CODE REVIEW

**Comment by timj** [comment]
This looks good to me but could the commit message explain the motivation please?

**Comment by fritzm** [comment]
Added the following comment to the commit:

"Existing code already sniffed the C++ compiler and provided
variable CXX_CXX11_FLAG which held the flags if any to be
passed to the compiler to enable the closest available
approximation to C++11.

Some eups applications now wish to move beyond C++11 to C++14.
This commit adds a new CXX_CXX14_FLAG which may be used for
this purpose, maintaining backward compatibility for applications
that may already be using CXX_CXX11_FLAG."

**Comment by RobertLuptonTheGood** [comment]
This is, of course, not really part of eups.  We should really split the eupspkg out from eups, but maybe it isn't worth it.

**Comment by fritzm** [comment]
I'm not sure I want to wade into the perturbations to e.g. LSST CI that would probably be created by undertaking the split...  But I'd be happy to further clarify the commit message?

**Comment by fritzm** [comment]
We now have:

> Existing code in the eupspkg.sh script currently bundled here
already sniffs the C++ compiler and provides variable
CXX_CXX11_FLAG; this is set to hold the flags, if any, to be passed
to the compiler from an eupspkg package script in order to enable
the closest available approximation to C++11.
> 
> Some eupspkg-built packages now wish to move beyond C++11 to C++14.
This commit adds a new CXX_CXX14_FLAG in eupspkg.sh which may be
used for this purpose, maintaining backward compatibility for
eupspkg package scripts that may already be using the existing
CXX_CXX11_FLAG.

**Pull request merged**
