### PR TITLE
Remove unused Product.persist() and .unpersist() methods

### PR DESCRIPTION
**Pull request by mjuric**
I found these while looking for other places that may have race conditions while pickling. I think they aren't used anywhere, and look like a leftover from an abandoned experiment. They may be confusing to newcomers, who may be tempted to use them.

### CODE REVIEW

**Comment by timj** [comment]
I think there's a test for these that would also have to be removed (in `testProduct.py:testPersist`).

**Comment by timj** [comment]
I rebased this pull request so that Travis would test it and it does fail (as expected) because the test is still looking for the `persist` method.

**Comment by timj** [comment]
Should we remove the test and merge this?

**Comment by RobertLuptonTheGood** [comment]
Sure, sorry I hadn't noticed this branch.  The code's from Ray Plante and (as Mario says) not used.

**Pull request merged**
